services:
  - type: web
    name: katalog
    runtime: docker
    plan: free
    repo: https://github.com/BagoesBaiq/Laravel
    branch: master
    dockerfilePath: ./Dockerfile
    autodeploy: true
    region: singapore
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Katalog
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://katalognusantara.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: katalog-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: katalog-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: katalog-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: katalog-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: katalog-db
          property: password
      - key: FILESYSTEM_DISK
        value: public
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: katalog-db
    plan: free
    typer: mysql
