services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: "./.render-build.sh"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
